# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ShaoPingWuLiu' do

end

target 'ShaoPingWuLiuTests' do

end
platform :ios, '7.0'
pod 'IQKeyboardManager'
pod 'AMap2DMap'    , '~>2.6.0'
pod 'AMapSearch'   , '~>2.6.0'
pod 'AFNetworking' ,'~>2.5.4'
pod 'MJRefresh'
pod 'MBProgressHUD'
